#!/bin/bash

echo -e "<div><style>span{color:orange;}</style><span>I hope you had a good time with NoiCloudInSettings 😊</span>"
echo -e "<div><style>span{color:orange;}</style><span>If you uninstalled NoiCloudInSettings because you had issues please report them to me!</span>"

curl -s --request GET "http://repo.bonventre.ch/counter.php?filename=NoiCloudInSettings.deb&action=remove" > /dev/null 2>&1
