#!/bin/bash

echo -e "<div><style>span{color:orange;}</style><span>Thank you for installing NoiCloudInSettings 😊</span>"
echo -e "<div><style>span{color:orange;}</style><span>Please send me some Feedback ✌️</span>"

curl -s --request GET "http://repo.bonventre.ch/counter.php?filename=NoiCloudInSettings.deb&action=add" > /dev/null 2>&1
